name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the site with Jekyll
      run: |
        docker run --rm \
          --volume="${{ github.workspace }}:/srv/jekyll" \
          -it jekyll/jekyll:latest \
          jekyll build
